import {
  Building2,
  Boxes,
  ChartColumn,
  ClipboardList,
  Database,
  Footprints,
  Globe,
  HandHeart,
  HeartHandshake,
  Home,
  Hospital,
  Landmark,
  LayoutDashboard,
  Map,
  MapPin,
  MessageSquare,
  Package,
  PackageCheck,
  PackageOpen,
  ScrollText,
  Snowflake,
  Route,
  Send,
  Settings,
  Store,
  Tent,
  Ticket,
  UserCog,
  UserRound,
  UserRoundCog,
  UserRoundCheck,
  Users,
  UtensilsCrossed,
  type LucideIcon,
} from 'lucide-react'

const icons: Record<string, LucideIcon> = {
  'layout-dashboard': LayoutDashboard,
  home: Home,
  users: Users,
  footprints: Footprints,
  tent: Tent,
  'user-cog': UserCog,
  'user-round-check': UserRoundCheck,
  'user-round-cog': UserRoundCog,
  'message-square': MessageSquare,
  settings: Settings,
  send: Send,
  'clipboard-list': ClipboardList,
  database: Database,
  globe: Globe,
  map: Map,
  'map-pin': MapPin,
  route: Route,
  'building-2': Building2,
  boxes: Boxes,
  'chart-column': ChartColumn,
  'utensils-crossed': UtensilsCrossed,
  hospital: Hospital,
  'heart-handshake': HeartHandshake,
  'hand-heart': HandHeart,
  landmark: Landmark,
  package: Package,
  'package-check': PackageCheck,
  'package-open': PackageOpen,
  'scroll-text': ScrollText,
  snowflake: Snowflake,
  store: Store,
  ticket: Ticket,
  'user-round': UserRound,
}

export function getNavIcon(name: string): LucideIcon {
  return icons[name] ?? LayoutDashboard
}
